# Site settings
title: Gaussian Process Summer School 2014
email: 
description: > # this means to ignore newlines until "baseurl:"
  The 2014 Gaussian Process Summer School held at the University of Sheffield.
baseurl: "/gpss14/" # the subpath of your site, e.g. /blog/
url: "https://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: gpschool/jekyll-theme
style: gpss


analytics:
  google:
    tracking_id: UA-62991754-1

youtube:
  height: 315
  width: 560

conference:
  draft: False
  hide_tentative: True
  hosts:
  short_name: GPSS
  full_name:  Gaussian Process Summer School  
  room: 
  venue: The University of Sheffield
  location: Sheffield, UK
  name: Gaussian Process Summer School
  year: 2015
  month: September
  hosts:
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: Zhenwen Dai, url: "http://staffwww.dcs.shef.ac.uk/people/Z.Dai/"}
  - {name: Sheffield ML Group, url: "http://sheffieldml.github.io"}
  name: Gaussian Process Summer School
  location: University of Sheffield, UK
  year: 2014
  dates:
  - {date: 15, day: Monday, month: September, year: 2014}
  - {date: 16, day: Tuesday, month: September, year: 2014}
  - {date: 17, day: Wednesday, month: September, year: 2014}
  - {date: 18, day: Thursday, month: September, year: 2014}

previous_meeting:
  name: GPSS Winter 2014
  url: "https://gpss.cc/gpws14"

# Build settings
markdown: kramdown
