# Site settings
title: Gaussian Process Summer School 2014
email: 
description: > # this means to ignore newlines until "baseurl:"
  The 2014 Gaussian Process Summer School held at the University of Sheffield.
baseurl: "/gpss14/" # the subpath of your site, e.g. /blog/
url: "https://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: gpschool/jekyll-theme
style: gpss


analytics:
  google:
    tracking_id: UA-62991754-1

youtube:
  height: 315
  width: 560

conference:
  draft: False
  hide_tentative: True
  hosts:
  short_name: GPSS
  full_name:  Gaussian Process Summer School  
  room: 
  venue: The University of Sheffield
  location: Sheffield, UK
  name: Gaussian Process Summer School
  year: 2014
  chairs:
  - type: Organizers
    people:
    - {given: Neil, family: Lawrence, url: "http://inverseprobability.com"}
    - {given: Zhenwen, family: Dai, url: "http://staffwww.dcs.shef.ac.uk/people/Z.Dai/"}
    - {given: Sheffield ML Group, url: "http://sheffieldml.github.io"}
  dates:
  - 2014-09-15
  - 2014-09-16
  - 2014-09-17
  - 2014-09-18

previous_meeting:
  name: GPSS Winter 2014
  url: "https://gpss.cc/gpws14"

# Build settings
markdown: kramdown
